# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aparcamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('access', models.CharField(max_length=2)),
                ('enlace', models.TextField()),
                ('contacto', models.TextField()),
                ('nomVia', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('barrio', models.CharField(max_length=50)),
                ('distrito', models.CharField(max_length=50)),
                ('latitud', models.TextField(blank=True)),
                ('longitud', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('aparcamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aparcamientos.Aparcamiento')),
            ],
        ),
        migrations.CreateModel(
            name='CSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seleccionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('aparcamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aparcamientos.Aparcamiento')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
