# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparcamiento',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='aparcamiento',
            name='nomVia',
        ),
        migrations.RemoveField(
            model_name='aparcamiento',
            name='numero',
        ),
        migrations.AlterField(
            model_name='aparcamiento',
            name='contacto',
            field=models.CharField(default='', max_length=150),
        ),
    ]
