# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0003_aparcamiento_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparcamiento',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
