# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0004_auto_20170517_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='aparcamiento',
            new_name='aparcamiento_id',
        ),
        migrations.RenameField(
            model_name='seleccionado',
            old_name='aparcamiento',
            new_name='aparcamiento_id',
        ),
    ]
