# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0005_auto_20170518_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='css',
            name='user',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
